require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'EasyStartMApp' do
  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"])

  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

  target 'EasyStartMAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #	flipper_post_install(installer)
  #end
end

target 'NotificationServiceExtension' do
  pod 'Firebase/Messaging'
end

target 'EasyStartMApp-tvOS' do
  # Pods for EasyStartMApp-tvOS

  target 'EasyStartMApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end