// export const SERVER_DOMAIN = 'https://easy-start-test.site'
export const SERVER_DOMAIN = 'https://es-admin-15.ru'
// export const SERVER_DOMAIN = 'https://easystart.conveyor.cloud'
// export const SERVER_DOMAIN = 'https://13f652c8.ngrok.io'
// export const SERVER_DOMAIN = 'https://95f7da52.ngrok.io'